server:
  port: 8090

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/pass-entry
    username: idk
    password: SomeUselessPassword02
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update